# Generated by Django 5.0 on 2024-01-05 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pic', models.ImageField(upload_to='media/pictures')),
                ('date', models.DateTimeField(auto_now=True)),
                ('updated', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(related_name='liked_by', to=settings.AUTH_USER_MODEL)),
                ('responsed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profile.postmodel')),
            ],
        ),
    ]
