# Generated by Django 5.0 on 2024-01-05 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pic',
            field=models.ImageField(blank=True, upload_to='media/pictures'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='responsed',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Profile.postmodel'),
        ),
    ]
