# Generated by Django 5.0 on 2024-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_postmodel_reposted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='responsed',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='responsed',
            field=models.ManyToManyField(blank=True, related_name='responsed_by', to='Profile.postmodel'),
        ),
    ]
