# Generated by Django 5.0 on 2024-01-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_remove_postmodel_responsed_postmodel_responsed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='responsed',
            field=models.ManyToManyField(blank=True, to='Profile.postmodel'),
        ),
    ]
