# Generated by Django 5.0 on 2024-01-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_postmodel_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
