# Generated by Django 5.0 on 2024-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_alter_postmodel_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
