# Generated by Django 5.0 on 2024-01-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_alter_postmodel_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='quoted',
            field=models.ManyToManyField(blank=True, to='Profile.postmodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
