# Generated by Django 5.0 on 2024-01-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_postmodel_quoted_alter_postmodel_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Profile.postmodel')),
            ],
        ),
    ]
