# Generated by Django 5.0 on 2023-12-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_customuser_customusermodel'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserModel',
            new_name='CustomUser',
        ),
    ]
